[package]
name = "archiinventory"
version = "0.1.0"
edition = "2024"

[dependencies.archipelago_rs]
#version = "2.1.1"
path = "../archipelago_rs"
default-features = false
features = ["native-tls"]

[dependencies.sanitise-file-name]
version = "1.0.0"

[dependencies.rand]
version = "0.10.1"

[dependencies.ureq]
version = "3.3.0"
default-features = false
features = ["gzip", "json", "native-tls"]

[dependencies.url]
version = "2.5.8"

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.150"

[dependencies.csv]
version = "1.4.0"

[dependencies.z85]
version = "3.0.7"

[dependencies.simd-normalizer]
version = "0.1.1"

[dependencies.eframe]
version = "0.34.2"
features = ["persistence"]

[dependencies.egui_extras]
version = "0.34.2"
default-features = false

[dependencies.rfd]
version = "0.17.2"
default-features = false
features = ["gtk3", "wayland"]

[dependencies.smol]
version = "2.0.2"

[dependencies.multiline-logger]
version = "0.2.1"
features = ["backtrace"]

[dependencies.anyhow]
version = "1.0.102"

[dependencies.hashbrown]
version = "0.17.1"
features = ["serde"]


[lints]
workspace = true
